create table if not exists public.rewritten_actions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  pair_key text not null,
  action_index integer not null,
  original_title text not null,
  original_reason text not null,
  rewritten_title text not null,
  created_at timestamptz not null default now(),
  unique (user_id, date, pair_key, action_index)
);

alter table public.rewritten_actions
  drop column if exists rewritten_reason;

alter table public.rewritten_actions enable row level security;

create policy "Users can read their rewritten actions"
  on public.rewritten_actions for select
  using (auth.uid() = user_id);

create policy "Users can create their rewritten actions"
  on public.rewritten_actions for insert
  with check (auth.uid() = user_id);
